use_frameworks!

platform :ios, '8.0'

target 'LejiaSDKFramework_Example' do
  pod 'LejiaSDKFramework', :path => '../'

  target 'LejiaSDKFramework_Tests' do
    inherit! :search_paths

    
  end
end
